[Variables]
FontColor=255,255,255,255
FontSize=15
FontFace=ITC Avant Garde Pro Xlt
ColorText=255,255,255,255

;-------------------------------

[prayTime]
StringAlign=LEFT
StringEffect=SHADOW
FontEffectColor=0,0,0,80
FontColor=#FontColor#
FontFace=ITC Avant Garde Pro Bk
FontSize=#FontSize#
AntiAlias=1

[prayTitle]
StringAlign=RIGHT
StringCase=NONE
StringEffect=SHADOW
FontEffectColor=0,0,0,80
FontColor=#ColorText#
FontFace=#FontFace#
FontSize=#FontSize#
AntiAlias=1

[hijriDate]
StringAlign=RIGHT
StringStyle=BOLD
StringEffect=SHADOW
FontEffectColor=100,100,100,80
FontColor=#FontColor#
FontFace=#FontFace#
FontSize=20
AntiAlias=1
StringCase=LOWER

